language: node_js
node_js:
  - '6'
  - '8'
  - '9'
sudo: required
services:
  - docker
before_script:
  - docker build -t postfix-milter ./test/fixtures/
  - docker run -d --net=host postfix-milter
after_success: npm run coveralls
